import type { CategoryInfo, Creator, FeedItem } from "./types";

// Demo content shown until real platform ingestion + Supabase are wired up.

export const creators: Record<string, Creator> = {
  fireship: {
    id: "fireship",
    avatarUrl: "https://unavatar.io/youtube/@fireship?fallback=false",
    name: "Fireship",
    handle: "@fireship",
    platform: "youtube",
    category: "Coding",
    gradient: "from-orange-400 to-rose-500",
    followed: true,
  },
  mkbhd: {
    id: "mkbhd",
    avatarUrl: "https://unavatar.io/youtube/@mkbhd?fallback=false",
    name: "Marques Brownlee",
    handle: "@mkbhd",
    platform: "youtube",
    category: "Technology",
    gradient: "from-red-400 to-rose-600",
    followed: true,
  },
  ltt: {
    id: "ltt",
    avatarUrl: "https://unavatar.io/youtube/@LinusTechTips?fallback=false",
    name: "Linus Tech Tips",
    handle: "@LinusTechTips",
    platform: "youtube",
    category: "Technology",
    gradient: "from-amber-400 to-orange-600",
    followed: true,
  },
  espnfc: {
    id: "espnfc",
    avatarUrl: "https://unavatar.io/facebook/ESPNFC?fallback=false",
    name: "ESPN FC",
    handle: "ESPN FC",
    platform: "facebook",
    category: "Football",
    gradient: "from-emerald-400 to-teal-600",
    followed: true,
  },
  fabrizio: {
    id: "fabrizio",
    avatarUrl: "https://unavatar.io/x/FabrizioRomano?fallback=false",
    name: "Fabrizio Romano",
    handle: "@FabrizioRomano",
    platform: "x",
    category: "Football",
    gradient: "from-sky-400 to-blue-600",
    followed: true,
  },
  athletic: {
    id: "athletic",
    avatarUrl: "https://unavatar.io/x/TheAthletic?fallback=false",
    name: "The Athletic",
    handle: "@TheAthletic",
    platform: "x",
    category: "Football",
    gradient: "from-zinc-400 to-zinc-600",
    followed: true,
  },
  anthropic: {
    id: "anthropic",
    avatarUrl: "https://unavatar.io/x/AnthropicAI?fallback=false",
    name: "Anthropic",
    handle: "@AnthropicAI",
    platform: "x",
    category: "AI",
    gradient: "from-orange-300 to-amber-500",
    followed: true,
  },
  huggingface: {
    id: "huggingface",
    avatarUrl: "https://unavatar.io/x/huggingface?fallback=false",
    name: "Hugging Face",
    handle: "@huggingface",
    platform: "x",
    category: "AI",
    gradient: "from-yellow-300 to-amber-500",
    followed: true,
  },
  formula1: {
    id: "formula1",
    avatarUrl: "https://unavatar.io/instagram/f1?fallback=false",
    name: "Formula 1",
    handle: "@f1",
    platform: "instagram",
    category: "Formula 1",
    gradient: "from-red-500 to-orange-600",
    followed: true,
  },
  waveform: {
    id: "waveform",
    avatarUrl: "https://unavatar.io/youtube/@Waveform?fallback=false",
    name: "Waveform",
    handle: "@Waveform",
    platform: "youtube",
    category: "Technology",
    gradient: "from-violet-400 to-purple-600",
    followed: true,
  },
  devstream: {
    id: "devstream",
    name: "CodeWithLena",
    handle: "@codewithlena",
    platform: "twitch",
    category: "Coding",
    gradient: "from-purple-400 to-fuchsia-600",
    followed: true,
  },
  mosseri: {
    id: "mosseri",
    avatarUrl: "https://unavatar.io/instagram/mosseri?fallback=false",
    name: "Adam Mosseri",
    handle: "@mosseri",
    platform: "threads",
    category: "Technology",
    gradient: "from-slate-400 to-zinc-600",
    followed: true,
  },
  xqc: {
    id: "xqc",
    avatarUrl: "https://unavatar.io/twitch/xqc?fallback=false",
    name: "xQc",
    handle: "@xqc",
    platform: "kick",
    category: "Gaming",
    gradient: "from-indigo-400 to-blue-600",
    followed: true,
  },
};

export const suggestedCreators: Creator[] = [
  {
    id: "3blue1brown",
    avatarUrl: "https://unavatar.io/youtube/@3blue1brown?fallback=false",
    name: "3Blue1Brown",
    handle: "@3blue1brown",
    platform: "youtube",
    category: "Science",
    gradient: "from-blue-400 to-indigo-600",
    suggestedBecause: "Similar to Fireship",
  },
  {
    id: "openai",
    avatarUrl: "https://unavatar.io/x/OpenAI?fallback=false",
    name: "OpenAI",
    handle: "@OpenAI",
    platform: "x",
    category: "AI",
    gradient: "from-teal-300 to-emerald-500",
    suggestedBecause: "You follow Anthropic",
  },
  {
    id: "veritasium",
    avatarUrl: "https://unavatar.io/youtube/@veritasium?fallback=false",
    name: "Veritasium",
    handle: "@veritasium",
    platform: "youtube",
    category: "Science",
    gradient: "from-cyan-400 to-sky-600",
    suggestedBecause: "High-quality educational video",
  },
  {
    id: "tifo",
    avatarUrl: "https://unavatar.io/youtube/@TifoFootball?fallback=false",
    name: "Tifo Football",
    handle: "@TifoFootball",
    platform: "youtube",
    category: "Football",
    gradient: "from-green-400 to-emerald-600",
    suggestedBecause: "You follow The Athletic",
  },
  {
    id: "syntax",
    avatarUrl: "https://unavatar.io/youtube/@syntaxfm?fallback=false",
    name: "Syntax",
    handle: "@syntaxfm",
    platform: "youtube",
    category: "Coding",
    gradient: "from-rose-400 to-pink-600",
    suggestedBecause: "Similar to Fireship",
  },
];

export const feedItems: FeedItem[] = [
  {
    id: "f1",
    reactions: 48200,
    creator: creators.fabrizio,
    type: "post",
    title:
      "Here we go! Midfield transfer saga finally complete — medical booked for tomorrow morning, five-year deal agreed.",
    aiSummary:
      "The long-running transfer is done: fee around €60m plus add-ons, announcement expected within 48 hours.",
    category: "Football",
    tags: ["news"],
    publishedAgo: "23m",
  },
  {
    id: "f2",
    reactions: 21400,
    creator: creators.fireship,
    type: "video",
    title: "TypeScript 6.0 in 100 seconds… and why your build just broke",
    aiSummary:
      "New compiler drops implicit any for real this time. Migration is one flag, but three popular libraries aren't ready yet.",
    category: "Coding",
    tags: ["educational"],
    publishedAgo: "1h",
    length: "2:47",
  },
  {
    id: "f3",
    reactions: 96500,
    creator: creators.formula1,
    type: "post",
    title: "Race weekend in photos: the undercut that decided the British GP",
    aiSummary:
      "Gallery from the pit wall: the lap-18 stop that won the race, plus the turn-4 clash the stewards are reviewing.",
    category: "Formula 1",
    tags: ["entertainment", "news"],
    publishedAgo: "2h",
  },
  {
    id: "f4",
    reactions: 33800,
    creator: creators.mkbhd,
    type: "video",
    title: "The Truth About Foldables in 2026: 3 Years Later",
    aiSummary:
      "Crease is basically solved, durability isn't. Battery tech is the real reason foldables still trail flagship slabs.",
    category: "Technology",
    tags: ["educational", "entertainment"],
    publishedAgo: "3h",
    length: "14:05",
  },
  {
    id: "f5",
    reactions: 15200,
    creator: creators.anthropic,
    type: "post",
    title:
      "New research: tracing how large models plan ahead when writing, and what that means for interpretability.",
    aiSummary:
      "Models appear to plan several tokens ahead. The paper shows a method for reading those plans out of activations.",
    category: "AI",
    tags: ["educational", "news"],
    publishedAgo: "4h",
  },
  {
    id: "f6",
    reactions: 7400,
    creator: creators.athletic,
    type: "article",
    title:
      "Tactical breakdown: why the high press stopped working after 60 minutes",
    aiSummary:
      "Fatigue changed the pressing shape from 4-2-4 to 4-4-2, opening the half-spaces that led to both late goals.",
    category: "Football",
    tags: ["educational"],
    publishedAgo: "5h",
    length: "6 min read",
  },
  {
    id: "f7",
    reactions: 3900,
    creator: creators.devstream,
    type: "stream",
    title: "Building a real-time multiplayer game in Rust — day 3",
    aiSummary:
      "Live now: netcode rollback implementation. Yesterday's session covered the lobby system and matchmaking.",
    category: "Coding",
    tags: ["educational", "live"],
    publishedAgo: "LIVE",
  },
  {
    id: "f8",
    reactions: 5600,
    creator: creators.waveform,
    type: "podcast",
    title: "Ep. 312 — The smartphone camera wars are over. Software won.",
    aiSummary:
      "Computational photography has plateaued hardware differences away; the hosts debate whether AI editing goes too far.",
    category: "Technology",
    tags: ["entertainment", "educational"],
    publishedAgo: "8h",
    length: "1:12:30",
  },
  {
    id: "f9",
    reactions: 28700,
    creator: creators.huggingface,
    type: "post",
    title:
      "New open weights release: a 3B model that matches last year's 70B on reasoning benchmarks. Runs on a phone.",
    aiSummary:
      "Distillation + new attention variant. Benchmarks look legit; community already shipped quantized builds.",
    category: "AI",
    tags: ["news", "educational"],
    publishedAgo: "9h",
  },
  {
    id: "f10",
    reactions: 61200,
    creator: creators.espnfc,
    type: "video",
    title: "Extended highlights: the 4-3 thriller everyone will talk about",
    aiSummary:
      "Two red cards, a 96th-minute winner, and a goalkeeper assist. Skip to 8:20 for the final ten minutes.",
    category: "Football",
    tags: ["entertainment"],
    publishedAgo: "11h",
    length: "12:41",
    saved: true,
  },
  {
    id: "f11",
    reactions: 44100,
    creator: creators.ltt,
    type: "video",
    title: "We built a PC entirely from parts found in e-waste",
    aiSummary:
      "Total cost: $0. It runs modern games at 1080p medium. The power supply was the only genuinely risky part.",
    category: "Technology",
    tags: ["entertainment"],
    publishedAgo: "1d",
    length: "22:18",
  },
  {
    id: "f12",
    reactions: 18900,
    creator: creators.fireship,
    type: "short",
    title: "POV: you deployed on Friday",
    aiSummary: "60-second sketch. Rollback jokes. You know how this ends.",
    category: "Coding",
    tags: ["entertainment"],
    publishedAgo: "1d",
    length: "0:58",
  },
];

export const categories: CategoryInfo[] = [
  { slug: "football", name: "Football", count: 14 },
  { slug: "technology", name: "Technology", count: 11 },
  { slug: "ai", name: "AI", count: 9 },
  { slug: "coding", name: "Coding", count: 8 },
  { slug: "formula-1", name: "Formula 1", count: 6 },
  { slug: "science", name: "Science", count: 5 },
  { slug: "finance", name: "Finance", count: 4 },
  { slug: "gaming", name: "Gaming", count: 4 },
  { slug: "music", name: "Music", count: 3 },
  { slug: "movies", name: "Movies", count: 3 },
  { slug: "books", name: "Books", count: 2 },
  { slug: "startups", name: "Startups", count: 2 },
];

export const digest = {
  greeting: "Good morning",
  items: [
    { label: "YouTube uploads", count: 6 },
    { label: "Instagram posts", count: 4 },
    { label: "News articles", count: 3 },
    { label: "Live streams", count: 2 },
  ],
};
