-- Flow is a public content aggregator: feed metadata is public content,
-- so let signed-out visitors read the feed too.
create policy "Feed items are publicly readable"
  on public.feed_items for select to anon using (true);

-- Seed the creator catalog.
insert into public.creators (name, handle, platform, category) values
  ('Fireship',         '@fireship',        'youtube', 'Coding'),
  ('Marques Brownlee', '@mkbhd',           'youtube', 'Technology'),
  ('Linus Tech Tips',  '@LinusTechTips',   'youtube', 'Technology'),
  ('ESPN FC',          '@ESPNFC',          'youtube', 'Football'),
  ('Fabrizio Romano',  '@FabrizioRomano',  'x',       'Football'),
  ('The Athletic',     'theathletic.com',  'rss',     'Football'),
  ('Anthropic',        '@AnthropicAI',     'x',       'AI'),
  ('Hugging Face',     '@huggingface',     'x',       'AI'),
  ('r/formula1',       'r/formula1',       'reddit',  'Formula 1'),
  ('Waveform',         'Waveform Podcast', 'podcast', 'Technology'),
  ('CodeWithLena',     '@codewithlena',    'twitch',  'Coding'),
  ('3Blue1Brown',      '@3blue1brown',     'youtube', 'Science'),
  ('OpenAI',           '@OpenAI',          'x',       'AI'),
  ('Veritasium',       '@veritasium',      'youtube', 'Science'),
  ('Tifo Football',    '@TifoFootball',    'youtube', 'Football'),
  ('Syntax',           'Syntax Podcast',   'podcast', 'Coding');

-- Seed demo feed items against the catalog (looked up by handle).
insert into public.feed_items
  (creator_id, platform, type, title, url, ai_summary, category, tags, duration_seconds, published_at)
select c.id, v.platform, v.type, v.title, v.url, v.ai_summary, v.category,
       v.tags::text[], v.duration_seconds, v.published_at::timestamptz
from (values
  ('@FabrizioRomano', 'x', 'post',
   'Here we go! Midfield transfer saga finally complete — medical booked for tomorrow morning, five-year deal agreed.',
   'https://x.com/FabrizioRomano',
   'The long-running transfer is done: fee around €60m plus add-ons, announcement expected within 48 hours.',
   'Football', '{news}', null, now() - interval '23 minutes'),
  ('@fireship', 'youtube', 'video',
   'TypeScript 6.0 in 100 seconds… and why your build just broke',
   'https://youtube.com/@fireship',
   'New compiler drops implicit any for real this time. Migration is one flag, but three popular libraries are not ready yet.',
   'Coding', '{educational}', 167, now() - interval '1 hour'),
  ('r/formula1', 'reddit', 'post',
   'Post-race debrief: how the undercut decided the British GP',
   'https://reddit.com/r/formula1',
   'Top comment argues the lap-18 pit call won the race; the stewards'' ruling on the turn-4 incident is the main controversy.',
   'Formula 1', '{entertainment,news}', null, now() - interval '2 hours'),
  ('@mkbhd', 'youtube', 'video',
   'The Truth About Foldables in 2026: 3 Years Later',
   'https://youtube.com/@mkbhd',
   'Crease is basically solved, durability is not. Battery tech is the real reason foldables still trail flagship slabs.',
   'Technology', '{educational,entertainment}', 845, now() - interval '3 hours'),
  ('@AnthropicAI', 'x', 'post',
   'New research: tracing how large models plan ahead when writing, and what that means for interpretability.',
   'https://x.com/AnthropicAI',
   'Models appear to plan several tokens ahead. The paper shows a method for reading those plans out of activations.',
   'AI', '{educational,news}', null, now() - interval '4 hours'),
  ('theathletic.com', 'rss', 'article',
   'Tactical breakdown: why the high press stopped working after 60 minutes',
   'https://theathletic.com',
   'Fatigue changed the pressing shape from 4-2-4 to 4-4-2, opening the half-spaces that led to both late goals.',
   'Football', '{educational}', 360, now() - interval '5 hours'),
  ('@codewithlena', 'twitch', 'stream',
   'Building a real-time multiplayer game in Rust — day 3',
   'https://twitch.tv',
   'Live now: netcode rollback implementation. Yesterday''s session covered the lobby system and matchmaking.',
   'Coding', '{educational,live}', null, now() - interval '10 minutes'),
  ('Waveform Podcast', 'podcast', 'podcast',
   'Ep. 312 — The smartphone camera wars are over. Software won.',
   'https://example.com/waveform',
   'Computational photography has plateaued hardware differences away; the hosts debate whether AI editing goes too far.',
   'Technology', '{entertainment,educational}', 4350, now() - interval '8 hours'),
  ('@huggingface', 'x', 'post',
   'New open weights release: a 3B model that matches last year''s 70B on reasoning benchmarks. Runs on a phone.',
   'https://x.com/huggingface',
   'Distillation plus a new attention variant. Benchmarks look legit; community already shipped quantized builds.',
   'AI', '{news,educational}', null, now() - interval '9 hours'),
  ('@ESPNFC', 'youtube', 'video',
   'Extended highlights: the 4-3 thriller everyone will talk about',
   'https://youtube.com/@ESPNFC',
   'Two red cards, a 96th-minute winner, and a goalkeeper assist. Skip to 8:20 for the final ten minutes.',
   'Football', '{entertainment}', 761, now() - interval '11 hours'),
  ('@LinusTechTips', 'youtube', 'video',
   'We built a PC entirely from parts found in e-waste',
   'https://youtube.com/@LinusTechTips',
   'Total cost: $0. It runs modern games at 1080p medium. The power supply was the only genuinely risky part.',
   'Technology', '{entertainment}', 1338, now() - interval '1 day'),
  ('@fireship', 'youtube', 'short',
   'POV: you deployed on Friday',
   'https://youtube.com/@fireship',
   '60-second sketch. Rollback jokes. You know how this ends.',
   'Coding', '{entertainment}', 58, now() - interval '1 day 2 hours')
) as v(handle, platform, type, title, url, ai_summary, category, tags, duration_seconds, published_at)
join public.creators c on c.handle = v.handle and c.platform = v.platform;
